import type { Metadata } from "next";
import { Geist, Inter, Poppins } from "next/font/google";
import "./../styles/globals.css";
import Nav from "@/components/nav";
import TabNavigation from "@/components/tabNavigation";
import SideBar from "@/components/sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${inter.variable} ${poppins.variable} antialiased max-md:select-none scroll-smooth`}
      >
        <div className="md:hidden">
          <Nav />
          {children}
          <TabNavigation />
        </div>
        <div className="max-md:hidden flex h-screen">
          <SideBar />
          <div className="p-8 overflow-auto h-full w-full flex justify-center items-start">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
